### ISSUE TITLE
Discord website crashing when entering chats.

### ISSUE THREAD

**Issue by lukeisbored** [Jazzzny/interweb55-snowleopard#6]
Exactly as the title says. Until a few days ago, the discord browser client worked flawlessly, but now when logging in (i have already emptied the cache and deleted all of the logins), for some reason the client 'encounters an issue', which i can only attribute to it not being able to connect to the servers properly. Is an update coming soon, or do you recommend reinstalling Interweb/Basilisk.app? I dont want to be stuck on using Discord Lite for chatting for too long, plus as an ex-SnowLion user i dont know if the browser client still works there. Thanks!
![Screeenshot as proof. Thank you for making this fantastic browser btw!](https://github.com/user-attachments/assets/d56c4164-7af4-4069-bf1a-93e69b6277dc)

**Comment by Jazzzny** [comment]
I am in the process of preparing a new release, which I hope should fix this.

**Comment by lukeisbored** [comment]
Understood, thank you so much! Hope there's no further issues while developing the update. :D

**Comment by Jazzzny** [comment]
Unfortunately, I wasn't able to determine the cause of Discord crashing in time for this release - it'll be out later today. I'll keep looking when I have the time, but for now, Discord will have to remain broken (unless they decide to fix it on their end, which has happened before).

**Comment by lukeisbored** [comment]
Oh, i see! Just updated, and indeed, it's still kinda broken. Still, performance is much better now, thank you!

**Comment by Lost-Entrepreneur439** [comment]
Can confirm it is still not working. I'm using the 64-bit build on 10.6.7.
